apiVersion: v1
kind: Deployment
metadata:
  name: cli
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cli
  template:
    metadata:
      labels:
        app: cli
    spec:
      containers:
        - image: codefresh-io/cli:latest
          name: cli
          ports:
            - containerPort: 80
