apiVersion: apps/v1
kind: Deployment
metadata:
  name: qtest
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: qtest
  template:
    metadata:
      labels:
        app: qtest
    spec:
      containers:
        - image: olehzahnitko/test:latest
          name: qtest
          ports:
            - containerPort: 80
