apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapi
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: testapi
  template:
    metadata:
      labels:
        app: testapi
    spec:
      containers:
        - image: gcr.io/codefresh-inc/codefresh/cf-api:test
          name: testapi
          ports:
            - containerPort: 80
