apiVersion: apps/v2
kind: Deployment
metadata:
  name: test1
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: test1
  template:
    metadata:
      labels:
        app: test1
    spec:
      containers:
        - image: olehzahnitko/test:latest
          name: test1
          ports:
            - containerPort: 80
