apiVersion: apps/v1
kind: Deployment
metadata:
  name: test1
spec:
  replicas: 2
  revisionHistoryLimit: 8
  selector:
    matchLabels:
      app: test1
  template:
    metadata:
      labels:
        app: test1
    spec:
      containers:
        - image: codefresh-io/cli:latest
          name: test1
          ports:
            - containerPort: 80
