apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapi
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: testapi
  template:
    metadata:
      labels:
        app: testapi
    spec:
      containers:
        - image: olehzahnitko/test:latest
          name: testapi
          ports:
            - containerPort: 1700
