apiVersion: apps/v1
kind: Deployment
metadata:
  name: cli
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: cli
  template:
    metadata:
      labels:
        app: cli
    spec:
      containers:
        - image: codefresh/cli:latest
          name: cli
          ports:
            - containerPort: 80
