apiVersion: apps/v2
kind: Deployment
metadata:
  name: test
spec:
  replicas: 1
  revisionHistoryLimit: 4
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - image: olehzahnitko/test:latest
          name: test
          ports:
            - containerPort: 80
